USE project;
CREATE TABLE Member(
Tno INT,
TName VARCHAR(50) NOT NULL,
Salary INT NOT NULL,
Area TEXT,
Age INT NOT NULL,
Grade CHAR(10) NOT NULL,
Department VARCHAR(50) NOT NULL,
PRIMARY KEY(Tno)
);

# TO SHOW THE STRUCTURE OF THE TABLE
DESCRIBE  project.Member;
# T INSERT RECORDS IN A TABLE
INSERT INTO Member VALUES
(1,'Tom',50000,'West',45,'C','Civil'),
(2,'Elsa',67000,'South',38,'A','Elec'),
(3,'Olivia',40000,'North',52,'B','Civil'),
(4,'Ethen',78000,'North',29,'B','Civil'),
(5,'Isabella',85000,'East',35,'A','Comp'),
(6,'James',52000,'South',34,'A','Mech');
 
 # TO DISPLAY ALL THE RECORDS OF THE TABLE
 SELECT * FROM project.Member;
 
 # TO DISPLAY TNO AND TNAME OF ALL THE EMPLOYEES FROM TABLE MEMBER
 SELECT TNo,TName FROM Member;
 
 # TO DROP THE CONSTRAINT OF DEPT
ALTER TABLE Member 
MODIFY Department VARCHAR(50) NULL;

# TO ADD ONE MORE COLUMN AS ADDRESS 20 CHAR AFTER TNAME
ALTER TABLE Member
ADD COLUMN Address VARCHAR(20) AFTER TName;

#  TO ADD COLUMN SNO AS INTERGER AS FRIST FIELD
ALTER TABLE Member
ADD COLUMN Sno INT FIRST;

# TO ADD COLUMN BONUS AS INTEGER AT THE END 
ALTER TABLE Member
ADD COLUMN Bonus INT AFTER Department;

# TO MODIFY THE DATA TYPE OF TNAME AS VARCHAR(30)
ALTER TABLE Member
MODIFY TName VARCHAR(30);

# DROP THE PRIMARY KEY CONSTRAINT
ALTER TABLE Member 
DROP PRIMARY KEY ;

# ADD A PRIMARY KEY CONSTRAINT TO TNAME
ALTER TABLE Member
ADD PRIMARY KEY(TName);

# TO DROP THE COLUMN AREA
ALTER TABLE Member
DROP COLUMN Area;

# TO DROP THE TABLE
DROP TABLE project.Member;











